### ISSUE TITLE
[Cata Classic] 1.06 doesn't implement the "Press key to show" option

### ISSUE THREAD

**Issue by Road-block** [osilvay/DisenchanterPlus#1]
Suggest changing the relevant function to 
```lua
function DP_EnchantingTooltip:ShowTooltip(itemInfo)
  local itemID = itemInfo.ItemID
  local isEnchantingItem = false
  local isItem = false

  local showTooltip = DP_CustomFunctions:IsKeyPressed(DisenchanterPlus.db.char.general.pressKeyDown)
  if not showTooltip then return end

  if DP_Database:GetEnchantingItemType(itemID) ~= nil then
    isEnchantingItem = true
  end

  if itemID == nil then return end
  --DisenchanterPlus:Debug("ShowTooltip [" .. tostring(itemID) .. "]")

  local _, _, itemQuality, _, _, itemType, _, _, _, _, _, _, _, _, _, _, _ = C_Item.GetItemInfo(itemID)
  --LogBook:Debug(string.format("itemQuality = %s - itemType = %s", tostring(itemQuality), tostring(itemType)))
  --if itemQuality == nil or itemType == nil or itemQuality < 2 then return end

  if itemType == DisenchanterPlus:DP_i18n("Armor") or itemType == DisenchanterPlus:DP_i18n("Weapon") then
    isItem = true
  end

  showTooltip = (isItem or isEnchantingItem)
  if not showTooltip then return end

  -- draw title
  local isShowItemID = DisenchanterPlus.db.char.general.showItemID
  local isShowTitle = DisenchanterPlus.db.char.general.showTitle
  local itemIDText = DP_CustomColors:Colorize(DP_CustomColors:CustomColors("ROWID"), tostring(itemID))
  if not isShowItemID then
    itemIDText = ""
  end

  if isShowTitle then
    local titleText = string.format("%s", DisenchanterPlus:MessageWithAddonColor(DisenchanterPlus:DP_i18n("Enchanting")))
    GameTooltip:AddLine(" ")
    GameTooltip:AddDoubleLine(titleText, itemIDText)
  end
  if isItem then
    DP_EnchantingTooltip:ProcessItem(itemID)
  elseif isEnchantingItem then
    DP_EnchantingTooltip:ProcessEnchantingItem(itemID)
  end
end
```

I added the 
```lua
  local showTooltip = DP_CustomFunctions:IsKeyPressed(DisenchanterPlus.db.char.general.pressKeyDown)
  if not showTooltip then return end
``` 
snippet early so it doesn't go through calling a bunch of methods if the user dynamic option is to not make tooltip additions at all.
Only other thing I changed is further down the second show/no show check to be
```lua
  showTooltip = (isItem or isEnchantingItem)
  if not showTooltip then return end
```
since with the earlier keypress check we can no longer rely on the showTooltip variable to be initialized to false.

**Comment by osilvay** [comment]
Thanks for your feedback. I'll apply the changes on version 1.0.7.

**Comment by Road-block** [comment]
Hey since I have your ear.
As you are only using the itemType return from GetItemInfo I would suggest switching over to the method that doesn't require a server round trip for item info.
It returns less fields but covers your needs and will always return them for valid items, while GetItemInfo requires them to also be cached by the client locally,

```lua
   local _, itemType, itemSubType, itemEquipLoc, itemIcon, classID, subClassID = C_Item.GetItemInfoInstant(itemID)
```

I also had a couple more bugs happen in use:
- Error on entering combat when the disenchanter frame hasn't been initialized yet (has not shown before in the session)
- Wrong detection of skill needed to disenchant items at lower levels. *Either the detection of Enchanting skill level is not working or the reference used for skill <-> itemlevel is wrong for Cataclysm Classic.*
  
![image](https://github.com/user-attachments/assets/f8feb7d7-1778-490b-8cc0-bc388e53a577)
![image](https://github.com/user-attachments/assets/72c5e005-517d-45e5-a02e-be3095d4d504)

I'll make separate issues for those.

**Comment by Road-block** [comment]
Afaik these are the correct skill <> itemlevel tables for Cataclysm Classic (and MoP Classic when that comes around).
https://warcraft.wiki.gg/wiki/Disenchanting

This reference https://warcraft.wiki.gg/wiki/Disenchanting_tables should still be valid for Cata / MoP without going back in history for the item level <> mats breakdown.

**Comment by osilvay** [comment]
I was checking the disenchantment table, but I think it's incomplete, right? The data beyond 333 is missing...

![image](https://github.com/user-attachments/assets/3ac763ff-5f2e-4984-81ab-1734dc1a84c4)

The link with then enchanting level seems correct.

I got the data from here https://www.wow-professions.com/cataclysm/disenchanting-table-cataclysm-classic , but of course, the classic data (level 1-60 items) doesn't correspond to the cataclysm data...

I'm separating the classic and cataclysm tables into different objects, but I would need the data from beyond 333....

**Comment by osilvay** [comment]
I think I'll take the classic part from https://www.wow-professions.com/cataclysm/disenchanting-table-cataclysm-classic (no enchanting level requirement for items 1-60) and fill in the missing cataclysm part from there as well.

The enchanting level for cataclysm I'll get from the link you sent me https://warcraft.wiki.gg/wiki/Disenchanting

**Comment by Road-block** [comment]
In Cataclysm Classic, there absolutely is a skill requirement for low level items.
You were probably looking at the Uncommon items tables. There are no greens of that itemlevel in Cataclysm.

I would trust the information on the warcraft wiki more than a different 3rd party site.

**Comment by Road-block** [comment]
I'll try to make a pull request with separate commits for various small issues like the ones here.
I can test some of it as I'm levelling a new Enchanter in Cataclysm Classic (main reason I found and started using your addon)

**Comment by Road-block** [comment]
To be more exact for the Uncommon items breakdown.
1. There are no uncommon items higher than 333 in Cataclysm Classic.
2. The tail end of the wiki table can be supplemented with the data from wow-professions.
   - 272-305: 75% dust, 22% lesser celestial, 3% small heavenly (for armor, weapons have the dust / essence % reversed)
   - 306-333: 75% dust, 22% greater celestial, 3% heavenly (for armor, weapons have the dust / essence % reversed)

**Comment by Road-block** [comment]
Also I think some of the sources are polluted with data from before all versions of the game had itemlevel available.
Min Required level doesn't enter the disenchant equations in Cataclysm Classic.

You don't need conditional logic for selecting between actual item level and min level required to equip.
Only itemlevel.

\* *My guess is that some of the player gathered references are from the 2005-2009 period when the game wasn't offering itemlevel through the API and people were theorycrafting itemlevel from minreq level*

**Comment by osilvay** [comment]
I've seen that there is a gap in item levels between 66 and 78, do I understand that in Cata Classic there are no such level ranges?

![image](https://github.com/user-attachments/assets/94f2a27a-e6cb-4a70-bacc-878e478214e4)

**Comment by Road-block** [comment]
That is correct for uncommon items.
https://www.wowhead.com/cata/items/armor/min-level:65/max-level:79/quality:2/group-by:level?filter=8;1;0#0-3+19

There is one L76 item but it has no source which means it was never implemented in the live game (sometimes the data harvesters get data from beta or ptr versions of the game with items that never made it into the live game)

**Comment by Road-block** [comment]
I'm going to test the alpha, I see a lot of changes :)

One thing I had added to my local copy was a sanity check to the DisenchantWindow.lua `:DisableButtions()` and `:EnableButtons()` methods with
```lua
if not DisenchanterPlusBaseFrame then return end
```
as the first line inside those methods.

The reason was that if the user has selected the option to not auto-load the base frame, first time you enter combat both methods error as the window has never shown and those widgets do not yet exist.

**Comment by Road-block** [comment]
I made this change to `:CheckSkillLevelForItem` to conform to the new structure and few items I tested seem to be detected properly now.
```lua
function DP_Database:CheckSkillLevelForItem(skillLevel, itemLevel, itemMinLevel, itemQuality)
  --DisenchanterPlus:Debug("skillLevel " .. tostring(skillLevel))
  --DisenchanterPlus:Debug("itemLevel " .. tostring(itemLevel))
  --DisenchanterPlus:Debug("itemMinLevel " .. tostring(itemMinLevel))
  --DisenchanterPlus:Debug("itemQuality " .. tostring(itemQuality))
  if DisenchanterPlus.IsClassic or DisenchanterPlus.IsHardcore or DisenchanterPlus.IsEra or DisenchanterPlus.IsEraSeasonal then return true end

  if skillLevel and itemLevel and itemQuality then
    local subTable
    if itemQuality == Enum.ItemQuality.Uncommon then
      subTable = skillLevelData.UNCOMMON
    elseif itemQuality == Enum.ItemQuality.Rare then
      subTable = skillLevelData.RARE
    elseif itemQuality == Enum.ItemQuality.Epic then
      subTable = skillLevelData.EPIC
    end
    if subTable then
      for i=#subTable,1,-1 do
        local minSkillLevel, minItemLevel, maxItemLevel = subTable[i][1], subTable[i][2], subTable[i][3]
        if itemLevel <= maxItemLevel and skillLevel >= minSkillLevel then
          return true
        end
      end
    end
  end
  return false
end
```

**Comment by osilvay** [comment]
I've uploaded a first version of how the disenchantment tables would look. It doesn't generate the disenchantment table for cataclysm yet, but it seems to work for classic-era (I can't test it in cataclysm). I've also added what you mentioned.

[disenchanting_tables.xlsx](https://github.com/user-attachments/files/18047867/disenchanting_tables.xlsx)

I think that for the percentages I'm going to keep the logic that they mention in wow-proffessions instead of the tables in warcraft-wiki.gg because it seems cleaner to me even if it's not 100% realistic...

![image](https://github.com/user-attachments/assets/19a4bb1b-65d1-47ca-acac-2fdc7261258c)

I don't know what you think.

**Comment by Road-block** [comment]
With the rng factor they're approximations anyway so I agree it won't make a difference to players if something is off by 2% of the theoretical yield.

So do whatever makes more sense for the addon implementation.

**Comment by Road-block** [comment]
This is a completely trivial request, but when you are eventually ready to make a new release package, can you remove this part from the ## Title: metadata `|cffffffffLog|r|cff57b6ffBook|r ` I'm going to guess it's a leftover from some other of your addons you used as a starter template.

It makes it hard to find the addon in the addon list since it's not listed where you'd expect it to be alphabetically 😄

**Comment by osilvay** [comment]
> This is a completely trivial request, but when you are eventually ready to make a new release package, can you remove this part from the ## Title: metadata `|cffffffffLog|r|cff57b6ffBook|r ` I'm going to guess it's a leftover from some other of your addons you used as a starter template.
> 
> It makes it hard to find the addon in the addon list since it's not listed where you'd expect it to be alphabetically 😄

Yep, you're right...

**Comment by Road-block** [comment]
1.07 looks great 👍🏻 

I made some minor adjustments to the cataclysm expected d/e tables but this ticket can be closed anyway, thanks for all the work.
These are cross-referenced from wowhead for itemlevel ranges.
line 75
```lua
        { 152, 232, "4-7x", DisenchanterPlus.EnchantingItems.infinite_dust, "1-2x", DisenchanterPlus.EnchantingItems.greater_cosmic_essence,    "1x", DisenchanterPlus.EnchantingItems.dream_shard,            nil, nil },
```
line 77
```lua
        { 306, 333, "2-5x", DisenchanterPlus.EnchantingItems.hypnotic_dust, "1-2x", DisenchanterPlus.EnchantingItems.greater_celestial_essence, "1x", DisenchanterPlus.EnchantingItems.heavenly_shard,         nil, nil },
```
_line 76 inbetween those 2 unchanged_
lines 94,95,96
```lua
        { 152, 232, "4-7x", DisenchanterPlus.EnchantingItems.infinite_dust, "1-2x", DisenchanterPlus.EnchantingItems.greater_cosmic_essence,    "1x", DisenchanterPlus.EnchantingItems.dream_shard,            nil, nil },
        { 272, 305, "1-4x", DisenchanterPlus.EnchantingItems.hypnotic_dust, "1-4x", DisenchanterPlus.EnchantingItems.lesser_celestial_essence,  "1x", DisenchanterPlus.EnchantingItems.small_heavenly_shard,   nil, nil },
        { 306, 333, "2-5x", DisenchanterPlus.EnchantingItems.hypnotic_dust, "1-4x", DisenchanterPlus.EnchantingItems.greater_celestial_essence, "1x", DisenchanterPlus.EnchantingItems.heavenly_shard,         nil, nil },
```
line 129
```lua
        { 360, 416, nil, nil, nil, nil, nil,    nil,                                                    "1-2x", DisenchanterPlus.EnchantingItems.maelstrom_crystal },
```
