### ISSUE TITLE
Error on manual / other addon d/e

### ISSUE THREAD

**Issue by Road-block** [osilvay/DisenchanterPlus#2]
This is another case where a method can try to reference the "not yet initialized" window making it error.

```text
1x ...DisenchanterPlus/Modules/Window/DisenchantWindow.lua:687: attempt to index upvalue 'DisenchanterPlusBaseFrame' (a nil value)
[string "@DisenchanterPlus/Modules/Window/DisenchantWindow.lua"]:687: in function `GetItemToDisenchant'
[string "@DisenchanterPlus/Modules/Disenchant/DisenchantProcess.lua"]:102: in function `UnitSpellCastStart'
[string "@DisenchanterPlus/Modules/Events/DisenchanterPlusEvents.lua"]:34: in function <...hanterPlus/Modules/Events/DisenchanterPlusEvents.lua:33>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 private = <table> {
 }
}
itemName = nil
itemLink = nil
itemIcon = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'DisenchanterPlusBaseFrame' (a nil value)"
DisenchanterPlusBaseFrame = nil

```

**Comment by Road-block** [comment]
DP_DisenchantProcess:UnitSpellCastStart calls 
DP_DisenchantWindow:GetItemToDisenchant() calls 
DisenchanterPlusBaseFrame.yesButton:GetAttribute() 
but the window + button don't yet exist as the disenchant cast was started from another source.

So it probably needs another sanity check for DisenchanterPlusBaseFrame in the GetItemToDisenchant() method.

**Comment by osilvay** [comment]
I haven't been able to reproduce it, but I've uploaded version 1.0.8.2 with that and other bugs I've seen.

Can you check if it's been fixed?

**Comment by Road-block** [comment]
The reproduction case should be.
1. Uncheck `Enable` for the Disenchant (auto disenchant option) _so the frame does not automatically show_
2. Use the disenchant spell to manually disenchant an item so the cast event happens.
   - A similar effect would probably happen using Molinari to modifier-click an item to disenchant in bags.

I will test the latest push but looking at the code I'm pretty sure it'll be resolved.

**Comment by osilvay** [comment]
Wait for v1.0.8.3... i see another bug with spellcasting events...

**Comment by osilvay** [comment]
V1.0.8.3 uploaded. With other bugs fixes.
Thanks for report.

**Comment by Road-block** [comment]
This no longer happens, issue can be closed :)
